package com.chrisds24.job_tracker_practice_v1.job;

import java.time.Instant;
import java.util.UUID;

import org.hibernate.annotations.Generated;

import com.chrisds24.job_tracker_practice_v1.member.Member;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;


// @Entity: Tells JPA that this class is an entity that should be persisted
//   and maps to a database table
// @Table(name = "job"): Tells JPA which database table this entity maps to
@Entity
@Table(name = "job")
public class Job {
    // @Id: Need to specify the primary key field
    // @Generated: Simply means that this field is generated by the database
    // - USE: import org.hibernate.annotations.Generated;
    //   -- NOT: import jakarta.annotation.Generated;
    // @ColumnDefault("gen_random_uuid()")
    // - NOT NEEDED since Hibernate isn't auto-generating my database
    @Id
    @Generated
    private UUID id;

    // I'm trying to represent a Job-Member entity relationship in JPA, so I'm
    //   using an @ManyToOne Membr member field instead of memberId
    // - NOTE: Only have one of memberId OR member. DO NOT USE BOTH
    //   -- We don't want to map the same database column twice, which requires
    //      additional configuration and can create confusion about which field
    //      controls the foreign key
    // @Column(name = "member_id", nullable = false)
    // private UUID memberId;

    @Column(nullable = false)
    private String title;

    @Column(nullable = false)
    private String company;

    // Why use type Instant?
    // - The actual Postgres column is "date_saved TIMESTAMPTZ NOT NULL DEFAULT
    //   NOW()"
    // - TIMESTAMPTZ represents a specific point in time. PostgreSQL normalizes
    //   the value internally to UTC
    // - Instant also represents a specific point on the UTC timeline
    //
    // insertable and updatable are both false
    // - We want to tell JPA that this field shouldn't be updatable or
    //   insertable through Hibernate-generated SQL statements since this field
    //   is purely database-generated and cannot be changed later
    //   -- NOTE: It is still possible to run a PostgreSQL query directly
    //      against the database
    //
    // name
    // - This is the name of the  column in the database schema
    //   We want to specify this since the name of the field in the entity
    //   is different from the one in the database
    @Column(
        name = "date_saved",
        nullable = false,
        insertable = false,
        updatable = false
    )
    @Generated
    // @ColumnDefault("NOW()")
    private Instant dateSaved;

    // TODO: Change this to an enum later
    @Column(nullable = false)
    private String status;

    @Column(name = "salary_min")
    private Integer salaryMin;

    @Column(name = "salary_max")
    private Integer salaryMax;

    // @ManyToOne: Many Job entities can reference one Member
    //
    // fetch = FetchType.LAZY
    // - Don't load the member when loading the job. Only load when it's
    //   needed
    //   -- This is in contrast to fetch = FetchType.EAGER
    //
    // @JoinColumn(name = "member_id")
    // - The foreign-key column that represents the relationship is job's
    //   member_id column
    //
    // IMPORTANT: This doesn't mean that there's an actual member column in the
    //   database. This only means that there's a member field for Job entities
    //   in the persistence context
    //
    // NOTE: @ManyToOne is EAGER by default, but we want to make it LAZY here
    //   so we usually don't need the member field when loading jobs
    // - We also don't want to potentially end up with N+1 queries when loading
    //   multiple jobs
    //
    // NOTE: Only have one of memberId OR member. DO NOT USE BOTH
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id", nullable = false)
    private Member member;

    // TODO: lastUpdated

    // Hibernate requires a no-arg constructor so it can create an empty
    //   instance of your entity when loading it from the database
    protected Job() {}
    
    // Hibernate doesn't need this, it only needs the no-arg constructor
    // - This is used when we want to create a new Job entity in application
    //   code
    // - Therefore, we don't want autogenerated fields like id and dateSaved here
    //
    // NOTE: Since we're using a member field (Member entity) instead of
    // memberId: 
    // - We require a member when creating a Job, but we don't want a setter
    //   for it since it shouldn't be modifiable after creation
    public Job(
        // UUID memberId,
        String title,
        String company,
        String status,
        Integer salaryMin,
        Integer salaryMax,
        Member member
    ) {
        // this.memberId = memberId;
        this.title = title;
        this.company = company;
        this.status = status;
        this.salaryMin = salaryMin;
        this.salaryMax = salaryMax;
        this.member = member;
    }

    // NOTE: Hibernate doesn't require getters/setters for it to work. But we
    //   need them in application code to get/set fields
    // We also shouldn't have a setter for something like id or dateSaved since
    //   those are not meant to be edited

    // Getters
    public UUID getId() { return id; }
    // public UUID getMemberId() { return memberId; }
    public String getTitle() { return title; }
    public String getCompany() { return company; }
    public Instant getDateSaved() { return dateSaved; }
    public String getStatus() { return status; }
    public Integer getSalaryMin() { return salaryMin; }
    public Integer getSalaryMax() { return salaryMax; }
    // NOTE: If using a Member field instead of memberId, need to use a
    //   Member's getId() method to get a Job's member id
    public Member getMember() { return member; }

    // Setters
    public void setTitle(String title) { this.title = title; }
    public void setCompany(String company) { this.company = company; }
    public void setStatus(String status) { this.status = status; }
    public void setSalaryMin(Integer salaryMin) { this.salaryMin = salaryMin; }
    public void setSalaryMax(Integer salaryMax) { this.salaryMax = salaryMax; }

    // NOTE: setMember() here means you're changing which Member the Job
    //   references.
    // - IMPORTANT: However, we don't want this since we don't want member to
    //   be changeable.
    // - Instead, set the member in the constructor since we want it to be
    //   unchangeable after Job creation
    // public void setMember(Member member) { this.member = member; }
}

// ********* NOTES **********
// JPA entities are used for database persistence, not for data transfer
//   or for representing the API contract
// - Therefore, we also need DTOs
//   -- We also need Mapper classes as a result
//
// spring.jpa.hibernate.ddl-auto=none
// - Disable Hibernate auto table-generation, since I already have an existing
//   PostgreSQL database
//
// @Generated vs @GeneratedValue
// - @Generated is a Hibernate annotation for a value generated by the
//   database, such as a default, trigger, or generated column
//   -- If I'm using PostgreSQL's DEFAULT gen_random_uuid(), then @Generated
//      can be used to describe this behavior
//   -- ***** IMPORTANT: There's no need for
//      @ColumnDefault("gen_random_uuid()") if Hibernate isn't auto-generating
//      my database
// - @GeneratedValue means the entity’s primary-key value is generated.
//   -- @GeneratedValue is specifically the JPA mechanism for identifier
//      generation, and its exact suitability depends on the ID generation
//      strategy you want Hibernate/JPA to use
//
// dateSaved: Why use Instant?
// - For the entity's dateSaved field, Instant is the correct type to use if
//   the actual Postgres column is "date_saved TIMESTAMPTZ NOT NULL DEFAULT
//   NOW()"
// - TIMESTAMPTZ represents a specific point in time. PostgreSQL normalizes
//   the value internally to UTC and converts it for display according to
//   the session timezone.
// - Instant also represents a specific point on the UTC timeline
