package com.chrisds24.job_tracker_practice_v1.job;

import java.time.Instant;
import java.util.UUID;

import org.hibernate.annotations.Generated;

import com.chrisds24.job_tracker_practice_v1.member.Member;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;


// @Entity: Tells JPA that this class is an entity that should be persisted
//   and maps to a database table
// @Table(name = "job"): Tells JPA which database table this entity maps to
@Entity
@Table(name = "job")
public class Job {
    // Job
    // ------------
    // id
    // title
    // company
    // dateSaved
    // status
    // salaryMin
    // salaryMax

    // @Id: Need to specify the primary key field
    // @Generated: Simply means that this field is generated by the database
    // - USE: import org.hibernate.annotations.Generated;
    //   -- NOT: import jakarta.annotation.Generated;
    // @ColumnDefault("gen_random_uuid()")
    // - NOT NEEDED since Hibernate isn't auto-generating my database
    @Id
    @Generated
    private UUID id;

    // @Column(name = "member_id", nullable = false)
    // private UUID memberId;

    @Column(nullable = false)
    private String title;

    @Column(nullable = false)
    private String company;

    // Why use type Instant?
    // - The actual Postgres column is "date_saved TIMESTAMPTZ NOT NULL DEFAULT
    //   NOW()"
    // - TIMESTAMPTZ represents a specific point in time. PostgreSQL normalizes
    //   the value internally to UTC
    // - Instant also represents a specific point on the UTC timeline
    //
    // insertable and updatable are both false
    // - We want to tell JPA that this field shouldn't be updatable or
    //   insertable through Hibernate-generated SQL statements since this field
    //   is purely database-generated and cannot be changed later
    //   -- NOTE: It is still possible to run a PostgreSQL query directly
    //      against the database
    //
    // name
    // - This is the name of the  column in the database schema
    //   We want to specify this since the name of the field in the entity
    //   is different from the one in the database
    @Column(
        name = "date_saved",
        nullable = false,
        insertable = false,
        updatable = false
    )
    @Generated
    // @ColumnDefault("NOW()")
    private Instant dateSaved;

    // TODO: Change this to an enum later
    @Column(nullable = false)
    private String status;

    @Column(name = "salary_min")
    private Integer salaryMin;

    @Column(name = "salary_max")
    private Integer salaryMax;

    // @ManyToOne: Many Job entities can reference one Member
    //
    // fetch = FetchType.LAZY
    // - Don't load the member when loading the job. Only load when it's
    //   needed
    //   -- This is in contrast to fetch = FetchType.EAGER
    //
    // @JoinColumn(name = "member_id")
    // - The foreign-key column that represents the relationship is job's
    //   member_id column
    //
    // IMPORTANT: This doesn't mean that there's an actual member column in the
    //   database. This only means that there's a member field for Job entities
    //   in the persistence context
    //
    // NOTE: @ManyToOne is EAGER by default, but we want to make it LAZY here
    //   so we don't potentially end up with N+1 queries when loading multiple
    //   jobs
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id", nullable = false)
    private Member member;

    // TODO: lastUpdated
    
    public Job(
        UUID id,
        String title,
        String company,
        Instant dateSaved
    ) {
        this.id = id;
        this.title = title;
        this.company = company;
        this.dateSaved = dateSaved;
    }

    // Getters
    public UUID getId() { return id; }
    public String getTitle() { return title; }
    public String getCompany() { return company; }
    public Instant getDateSaved() { return dateSaved; }

    // Setters
    public void setId(UUID id) { this.id = id; }
    public void setTitle(String title) { this.title = title; }
    public void setCompany(String company) { this.company = company; }
    public void setDateSaved(Instant dateSaved) { this.dateSaved = dateSaved; }
}

// ********* NOTES **********
// JPA entities are used for database persistence, not for data transfer
//   or for representing the API contract
// - Therefore, we also need DTOs
//   -- We also need Mapper classes as a result
//
// spring.jpa.hibernate.ddl-auto=none
// - Disable Hibernate auto table-generation, since I already have an existing
//   PostgreSQL database
//
// @Generated vs @GeneratedValue
// - @Generated is a Hibernate annotation for a value generated by the
//   database, such as a default, trigger, or generated column
//   -- If I'm using PostgreSQL's DEFAULT gen_random_uuid(), then @Generated
//      can be used to describe this behavior
//   -- ***** IMPORTANT: There's no need for
//      @ColumnDefault("gen_random_uuid()") if Hibernate isn't auto-generating
//      my database
// - @GeneratedValue means the entity’s primary-key value is generated.
//   -- @GeneratedValue is specifically the JPA mechanism for identifier
//      generation, and its exact suitability depends on the ID generation
//      strategy you want Hibernate/JPA to use
//
// dateSaved: Why use Instant?
// - For the entity's dateSaved field, Instant is the correct type to use if
//   the actual Postgres column is "date_saved TIMESTAMPTZ NOT NULL DEFAULT
//   NOW()"
// - TIMESTAMPTZ represents a specific point in time. PostgreSQL normalizes
//   the value internally to UTC and converts it for display according to
//   the session timezone.
// - Instant also represents a specific point on the UTC timeline
